In [55]:
import pandas as pd
import numpy as np
from sklearn.manifold import MDS
import codecs, json 

In [38]:
df = pd.read_csv("10yearAUSOpenMatches.csv")
df = df.dropna()
wd = df.as_matrix(columns = df.columns[range(9, 37, 2)])
ld =  df.as_matrix(columns = df.columns[range(10, 37, 2)])
wd = wd.astype(float)
ld = ld.astype(float)

/home/local/ASUAD/usoni1/virtual_environments/venv_3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until
/home/local/ASUAD/usoni1/virtual_environments/venv_3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  after removing the cwd from sys.path.


In [37]:
len(wd)

800

In [45]:
final_data = (np.concatenate((wd, ld)))
final_data.shape

(1600, 14)

In [46]:
embedding = MDS(n_components=2)
td = embedding.fit_transform(final_data)
td.shape

(1600, 2)

In [47]:
td

array([[ 63.57098921, -24.83376845],
       [ 92.9906657 ,   5.03195558],
       [ -3.56356276,   5.53099188],
       ...,
       [ 37.72138703,   0.75786599],
       [ 32.98495043,   3.69125894],
       [  1.65172971,  18.4107965 ]])

In [48]:
td[0]

array([ 63.57098921, -24.83376845])

In [49]:
td[801]

array([108.5918181 , -36.65634238])

In [51]:
td[1]

array([92.9906657 ,  5.03195558])

In [52]:
td[900]

array([-35.90552093,  19.5971109 ])

In [53]:
td[1599]

array([ 1.65172971, 18.4107965 ])

In [54]:
td[799]

array([ 16.66820718, -28.88514228])

In [58]:
td = td.tolist() # nested lists with same data, indices
file_path = "/mds_data.json" ## your path variable
json.dump(td, codecs.open(file_path, 'w', encoding='utf-8'), separators=(',', ':'), sort_keys=True, indent=4) 

PermissionError: [Errno 13] Permission denied: '/mds_data.json'

In [59]:
td

[[63.57098921276359, -24.833768448528474],
 [92.9906656950627, 5.031955578807766],
 [-3.5635627609901896, 5.530991883875714],
 [-15.540567873671913, -24.774860994166033],
 [1.681930715522589, -70.60112818065461],
 [-1.1769144872286987, -49.36615649477987],
 [-27.428426864183972, -12.630709652253229],
 [3.207186982445155, -16.152434307641453],
 [-29.629074139509655, 3.0208191058922553],
 [40.86857211543891, 13.168079409606463],
 [17.969722756431395, -29.20910300871214],
 [-29.787047003757543, -46.28618085495564],
 [48.37739769409427, -44.50757615708225],
 [42.9073770416236, 0.9575462198392515],
 [2.7484239332332554, -14.024481241861766],
 [92.87974294568862, -35.93129341478993],
 [-13.212534755006327, -4.289668859156107],
 [-31.016894607808567, -21.92781483119204],
 [1.7816476222567463, 0.5040898607529931],
 [-30.348909452944312, -13.465992929165393],
 [8.146047631903341, 44.21825968801701],
 [1.1371493478835217, -10.90831839261739],
 [-41.52473700491768, -29.410495017066527],
 [-24.447